kit:
  name: "Mongodb"
  link: https://github.com/qubell-bazaar/component-mongodb
  applications:
    - name: "Mongo"
      manifest: https://raw.github.com/qubell-bazaar/component-mongodb/1.0-38p/component-mongodb.yml
  provider:
    name: "Qubell"
    link: http://qubell.com
  documentation:
    overview: |
      This application requires the following items to be configured in your environment:
        * CloudServers account;
        * Ports 27017 open on the ﬁrewall.
      Please refer to the Getting Started for step-by-step instructions on how to configure your environment.
